### ISSUE TITLE
Kernel module gets killed after loading it with modprobe

### ISSUE THREAD

**Issue by Betaminos** [cyring/CoreFreq#353] opened 2022-07-28 10:20 UTC
Hello there,

thank you very much for this great application and the continued support :)
After having used it for some time on my  devices, I seem to have stumbled across one or two bugs (I have opened the other one here: #352 ).
My device is based around an Intel 1165G7 and I am running Arch Linux, up to date as of now, with the default kernel (5.18.14-arch1-1.1).
(CoreFreq did previously - as in a few months back - work on this device, but I have no idea when it stopped working or what has changed)
In case it helps, this is my kernel cmdline:
`[beta@oxp ~]$ cat /proc/cmdline 
initrd=\intel-ucode.img initrd=\initramfs-linux.img root=PARTUUID=ff8e6e69-b43b-4477-8a1a-34f4705c3f88 zswap.enabled=0 rootflags=subvol=/@ rw rootfstype=btrfs processor.max_cstate=9 intel_idle.max_cstate=9 nmi_watchdog=0 nowatchdog`

I have installed CoreFreq via yay and have selected the non-git versions:
`yay corefreq-client corefreq-server corefreq-dkms
`

When I do the "sudo modprobe corefreqk", I only get a "Killed" as reply.
Repeating the same command results in the command getting stuck (?), where nothing will happen unless I cancel out of it with [CTRL]+[C]. 

As the installation via YaY did not show any errors, I am confused as to what is happening.
Please let me know if I can provide any additional information that can be of help here.

Thank you for your time.

**Comment by cyring** [comment] 2022-07-29 04:31
duplicate of #352

**Closed by cyring** 2022-07-29 04:31 UTC
